export {default as Header} from './header.jsx'
export {default as LandingPage} from './landingpage.jsx'
export {default as Footer} from './footer.jsx'
export {default as Register} from './registerpage.jsx'
export {default as Login} from './loginpage.jsx'
export {default as Dashboard} from './dashboard.jsx'
export {default as SingleFood} from './singlefood.jsx'
export {default as FoodSwap} from './foodswap.jsx'