export {default as Header} from './header.jsx'
export {default as LandingPage} from './landingpage.jsx'
export {default as Footer} from './footer.jsx'
export {default as Register} from './registerpage.jsx'
export {default as Login} from './loginpage.jsx'